name: keymap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware && qmk setup
    - name: Copy custom keymap definition
      run: cp -rp $(pwd)/crkbd3/keymap $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/nobleascent
    - name: Build firmware for right hand
      run:  cd qmk_firmware && make crkbd:nobleascent:avrdude-split-right
    - name: Build firmware for left hand
      run:  cd qmk_firmware && make crkbd:nobleascent:avrdude-split-left
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Hex files
        path: qmk_firmware/*.hex
    
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qmk_firmware/*.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}