name: keymap

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
    - name: Setup QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware
        make git-submodule
        qmk setup

    - name: Copy custom keymap definition
      run: cp -rp $(pwd)/crkbd3/keymap $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/nobleascent

    - name: Build custom firmware
      shell: bash
      run: cd qmk_firmware && timeout 10s qmk compile -kb crkbd -km nobleascent || [[ $? -eq 124 ]]
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Hex files
        path: qmk_firmware/*.hex
        
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qmk_firmware/crkbd_rev1_nobleascent.hex
