name: keymap

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
    - name: Setup QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware
        make git-submodule
        qmk setup

    - name: Copy custom keymap definition
      run: cp -rp $(pwd)/crkbd3/keymap $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/nobleascent

    - name: Build firmware for both hands
      run: |
        cd qmk_firmware
        timeout --foreground -k 10 1m qmk compile -kb crkbd -km nobleascent:avrdude-split-right || ( [[ $? -eq 124 ]] && echo "WARNING: Timeout reached, but that's OK" )
        timeout --foreground -k 10 1m qmk compile -kb crkbd -km nobleascent:avrdude-split-left || ( [[ $? -eq 124 ]] && echo "WARNING: Timeout reached, but that's OK" )
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Hex files
        path: qmk_firmware/*.hex