name: keymap

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v2
    - name: Setup QMK Firmware
      run: |
        git submodule update --init
        cd qmk_firmware
        make git-submodule
        qmk setup

    - name: Copy custom keymap definition
      run: cp -rp $(pwd)/crkbd3/keymap $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/nobleascent

    - name: Build firmware for both hands
      run: |
        cd qmk_firmware
        timeout 1.5m qmk compile -kb crkbd -km nobleascent:avrdude-split-right
        timeout 1.5m qmk compile -kb crkbd -km nobleascent:avrdude-split-left
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Hex files
        path: qmk_firmware/*.hex