name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install gcc unzip wget zip gcc-avr binutils-avr avr-libc dfu-programmer dfu-util gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
    - name: Update QMK Firmware
      run: |
        git submodule update --init
        ./qmk_firmware/util/qmk_install.sh
        cd qmk_firmware && make git-submodule
    - name: Copy custom keymap definition
      run: cp -rp $(pwd)/crkbd3/keymap $(pwd)/qmk_firmware/keyboards/crkbd/keymaps/nobleascent
    - name: Build firmware for right hand
      run:  cd qmk_firmware && make crkbd:nobleascent:avrdude-split-right
    - name: Build firmware for left hand
      run:  cd qmk_firmware && make crkbd:nobleascent:avrdude-split-left
      
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Hex files
        path: qmk_firmware/*.hex
    
    - name: Release
      uses: docker://softprops/action-gh-release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: qmk_firmware/*.hex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}